### ISSUE TITLE
NPE when calling HttpMessageContext.doNothing() from secureResponse.

### ISSUE THREAD

**Issue by sameer-pandit** [javaee/security-soteria#112]
When HttpMessageContext.doNothing() is called from secureResponse in HAM, the notifyContainerAboutLogin() call is made with null clientSubject. Jaspic.notifyContainerAboutLogin() should handle null values of clientSubject.

**Comment by sameer-pandit** [comment]
Exception stacktrace:
java.lang.NullPointerException
        at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler$2.run(BaseContainerCallbackHandler.java:440)
        at com.sun.enterprise.security.common.AppservAccessController.doPrivileged(AppservAccessController.java:61)
        at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallerPrincipal(BaseContainerCallbackHandler.java:438)
        at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallback(BaseContainerCallbackHandler.java:198)
        at com.sun.enterprise.security.jmac.callback.ServerContainerCallbackHandler.handleSupportedCallbacks(ServerContainerCallbackHandler.java:76)
        at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.handle(BaseContainerCallbackHandler.java:188)
        at com.sun.enterprise.security.jmac.callback.ContainerCallbackHandler.handle(ContainerCallbackHandler.java:83)
        at org.glassfish.soteria.mechanisms.jaspic.Jaspic.notifyContainerAboutLogin(Jaspic.java:199)
        at org.glassfish.soteria.mechanisms.HttpMessageContextImpl.doNothing(HttpMessageContextImpl.java:297)
        at com.sun.ts.tests.securityapi.ham.workflow.secureresponse.TestAuthenticationMechanism.secureResponse(TestAuthenticationMechanism.java:60)
        at com.sun.ts.tests.securityapi.ham.workflow.secureresponse.TestAuthenticationMechanism$Proxy$_$$_WeldClientProxy.secureResponse(Unknown Source)
        at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.secureResponse(HttpBridgeServerAuthModule.java:137)

**Comment by wmhopkins** [comment]
@sameer-pandit -- this is not a valid use case. The `secureResponse()` method is called to secure a response that's about to be sent back to the client, typically after the servlet has already been invoked. The `HttpMessageContext` is passed to provide access to the JASPIC `MessageInfo` object, and to other bits of state about the request. It is not intended that `notifyContainerAboutLogin()` would ever be called from `secureResponse()`.

Closing this as **not a bug**.
