### ISSUE TITLE
Can't specifiy expression values for ENUM property expression. ( Such as useForExpression, searchScopeExpression)

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#120]
@DatabaseIdentityStoreDefinition(
	   dataSourceLookup="jdbc/securityAPIDB",	     
	    callerQuery="select password from caller where name = ?",
	    groupsQuery="select group_name from caller_groups where caller_name = ?",
	    useFor={ValidationType.VALIDATE},
	    priority=100,
	    useForExpression="#{{ValidationType.PROVIDE_GROUPS}}",
	    hashAlgorithm = PlaintextPasswordHash.class
)

Below exception always appears when set  useForExpression directly (as above) instead of bean property.
Similar issue for caller/groupSearchScopeExpression

[2017-07-25T01:48:26.944-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=31 _ThreadName=Thread-9] [timeMillis: 1500972506944] [levelValue: 1000] [[
  javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier 'ValidationType'                                      
        at com.sun.el.lang.ELSupport.throwUnhandled(ELSupport.java:68)                                                                                  
        at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:126)                                                                             
        at com.sun.el.parser.AstValue.getBase(AstValue.java:151)                                                                                        
        at com.sun.el.parser.AstValue.getValue(AstValue.java:200)                                                                                       
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)                                                                        
        at javax.el.ELProcessor.getValue(ELProcessor.java:129)                                                                                          
        at javax.el.ELProcessor.eval(ELProcessor.java:115)                                                                                              
        at org.glassfish.soteria.cdi.AnnotationELPProcessor.evalELExpression(AnnotationELPProcessor.java:142)                                           
        at org.glassfish.soteria.cdi.AnnotationELPProcessor.evalELExpression(AnnotationELPProcessor.java:133)                                           
        at org.glassfish.soteria.cdi.DatabaseIdentityStoreDefinitionAnnotationLiteral.useFor(DatabaseIdentityStoreDefinitionAnnotationLiteral.java:167)

**Comment by ggam** [comment]
Constants/enums have to be imported on Expression Language (see slide 11 on https://es.slideshare.net/reza_rahman/whats-new-with-expression-language-in-java-ee-7).

You'll need to create a managed bean that returns the desired value from a method.

**Comment by arjantijms** [comment]
>Constants/enums have to be imported on Expression Language (see slide 11 on https://es.slideshare.net/reza_rahman/whats-new-with-expression-language-in-java-ee-7).

Indeed, although just like JSF does, I did added the ability to coerce the non-qualified String variant of the enum name.

The following should work:

```java
useForExpression="#{'PROVIDE_GROUPS'}'",
```

**Comment by ggam** [comment]
@arjantijms Is that something you've manually done or is it already provided by EL? I mean, would it work on other implementations or is this a Soteria specific feature?

**Comment by arjantijms** [comment]
I've added it myself indeed. If we specify that it the string corresponds to the name of one of the values of the target enum, why should it not be portable?

That said, I was going to try if the `coerce()` method on the factory might give the same results. Want to try that for Long to Integer etc conversion as well.

**Comment by ggam** [comment]
> If we specify that it the string corresponds to the name of one of the values of the target enum, why should it not be portable?

That would definitely make it portable ;). Is that already written somewhere? I haven't seen it myself, hence my concern.

**Comment by arjantijms** [comment]
It indeed still needs to be done. So many tiny little things, eating up lots of time ;)

**Comment by ggam** [comment]
@wmhopkins I think this issue can be closed. As @arjantijms pointed out, the correct syntax would be `#{'PROVIDE_GROUPS'}'` which is indeed consistent with JSF.

We should however document this somwhere, since this particular feature hasn't made into the spec.

**Comment by wmhopkins** [comment]
@ggam, @arjantijms -- So, in essense, the ability to use 'PROVIDE_GROUPS' or other enum values is an EL language extension implemented by Soteria, but not documented?

I have a couple thoughts on this. The first is that, since it's not documented, the TCK shouldn't test for it. The second is that, if the TCK tests for it, it becomes de facto standard. ;)

Does Arjan's code support all the possible enum values for all the annotation attributes that take enums? If so, then it's probably worth trying to sneak it in via the TCK. If not, then it might be better to take it out of the RI and TCK, and say that only standard EL is supported. Otherwise, we'll be encouraging implementations to provide inconsistent and non-standard EL syntax.

**Comment by ggam** [comment]
Yes @wmhopkins Arjan's code just converts whatever value is passed to the equivalent in the enum: https://github.com/javaee/security-soteria/blob/42279b32722f58c6be37c3f65faab0c91b68598a/impl/src/main/java/org/glassfish/soteria/cdi/AnnotationELPProcessor.java#L147

As you can see its just some lines of code, and moreover, it works exactly the same way on JSF, so people might expect this to work (I even thought for a long time this was an EL feature rather than JSF).

I think it would be good to test this on the TCK as it should not be a problem for implementors. But definitely this should be spec'ed on the next release.

**Comment by arjantijms** [comment]
>Does Arjan's code support all the possible enum values for all the annotation attributes that take enums?

Indeed it does. If just checks if the string outcome is a name in the target enum, and if so returns the enum constant corresponding to that name.

It's a petty we missed this in the spec text as it would have been such a small thing to put in javadoc, but it is what it is. In JASPIC 1.1 last time we also missed a small thing like that. 

Additionally, I wanted to see if the `coerce()` method of the el factory could have been used by default as well, but that too just missed the deadline.

I'm okay with whatever way this goes; put it in via the TCK, remove it, or keep it as RI feature. Since it works exactly the same as EL in JSF, it's highly expected that it works like this.

At any length we may want to aim for a small MR before long, to clarify this point and perhaps some other small things.

**Comment by wmhopkins** [comment]
So I guess we could leave this code in the RI, then. Whether the TCK should use the capability is another question, because it essentially then becomes a "shadow standard" -- not documented, but required, ilke the JASPIC "special move".

On the other hand, if this is typical syntax that developers will expect to work, that's not so bad -- I'm OK with the TCK using this syntax.

I agree we're going to need an MR (or at least errata) soon.

**Comment by wmhopkins** [comment]
@wxwesther -- As noted above, the correct syntax for this is `#{'PROVIDE_GROUPS'}`. Closing this as working as designed.

**Comment by ggam** [comment]
>Additionally, I wanted to see if the coerce() method of the el factory could have been used by default as well, but that too just missed the deadline.

@arjantijms I think I solved that yesterday via #166. Do you meant that?

**Comment by arjantijms** [comment]
@ggam 
>I think I solved that yesterday via #166. Do you meant that?

Well not exactly that, but it would be applied to the same case indeed. There's an actual `coerce()` method in the bean validation API, that I guess would do what it says; coerce values. Just haven't been able to try it out yet.

**Comment by ggam** [comment]
@arjantijms but that would also bring a dependency on bean validation, right? Are we allowed to do that without requiring it at spec level?

**Comment by wmhopkins** [comment]
If we have something that works, I think that's good enough for now. Are there any types that we aren't correctly handling yet?

**Comment by arjantijms** [comment]
@ggam
>but that would also bring a dependency on bean validation, right? Are we allowed to do that without requiring it at spec level?

Sorry, I was just working on bean validation while I quickly typed a reply here. It should be "expression language" where the coerce method is located ;)

**Comment by arjantijms** [comment]
>If we have something that works, I think that's good enough for now. Are there any types that we aren't correctly handling yet?

It's technically 100% covered, it would just theoretically allow for some implementation code to be replaced by a call to an existing method.

**Comment by wmhopkins** [comment]
If that's the case, then I think it's an excellent idea for the next version of the RI, but not a functional issue and hence not a priority for this version.
