### ISSUE TITLE
Better to use default or specified caller/groupSearchScope value if *searchScopeExpression is invalid

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#130]
```
@LdapIdentityStoreDefinition(
	    url = "ldap://localhost:11389/",
		callerSearchBase = "ou=caller,dc=securityapi,dc=net",
	    callerSearchFilter = "(&(uid=%s)(objectClass=person))",
	    callerSearchScope = LdapSearchScope.SUBTREE,  
	    callerSearchScopeExpression = "${configBean.priority}",
	    groupSearchBase  = "ou=group,dc=securityapi,dc=net",
	    groupSearchScope = LdapSearchScope.SUBTREE,
	    groupSearchScopeExpression = "${configBean.searchScopeOneLevel_invalid}"
	)
```

Specified invalid expression, below server exception appears and no validation result return.
IMHO, better to use the default of specified caller/groupSearchScope value, and return expected validation result .
```

[2017-07-25T19:39:33.591-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=31 _ThreadName=Thread-9] [timeMillis: 1501036773591] [levelValue: 1000] [[
  javax.el.PropertyNotFoundException: The class 'com.sun.ts.tests.securityapi.idstore.common.ConfigBean' does not have the property 'priority'.         
        at javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:731)                                                                             
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:351)                                                                                    
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:188)                                                                          
        at com.sun.el.parser.AstValue.getValue(AstValue.java:140)                                                                                       
        at com.sun.el.parser.AstValue.getValue(AstValue.java:204)                                                                                       
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)                                                                        
        at javax.el.ELProcessor.getValue(ELProcessor.java:129)                                                                                          
        at javax.el.ELProcessor.eval(ELProcessor.java:115)                                                                                              
        at org.glassfish.soteria.cdi.AnnotationELPProcessor.evalELExpression(AnnotationELPProcessor.java:142)                                           
        at org.glassfish.soteria.cdi.AnnotationELPProcessor.evalELExpression(AnnotationELPProcessor.java:133)                                           
        at org.glassfish.soteria.cdi.LdapIdentityStoreDefinitionAnnotationLiteral.callerSearchScope(LdapIdentityStoreDefinitionAnnotationLiteral.java:238)

```

**Comment by wxwesther** [comment]
Similar issue for priorityExpression and useForExpression. 
If  priorityExpression is invalid, then use the default value of priority 
If useForExpression is inalid, then use the default value of useFor

**Comment by arjantijms** [comment]
>If priorityExpression is invalid, then use the default value of priority
>If useForExpression is inalid, then use the default value of useFor

This in a way is the opposite of what some of the other threads have been asking for, i.e. fail deployment when an invalid expression is detected instead of using the default silently.

**Comment by ggam** [comment]
Silently using the default one is not an option IMO as we don't even have a
way to see if the value of the annotation was set by the user.

**Comment by arjantijms** [comment]
I'd not be a big fan of that indeed.

**Comment by wmhopkins** [comment]
I agree that silently defaulting to some other value would be the wrong thing to do.

What is the right thing to do here? We've discussed the issue of how to fail gracefully from bad config, but haven't really arrived at a good answer -- we've only determined that we can't reliably fail at depoy time because idstores and hams may not be application scoped.

What's the guidance for apps/app developers/dev_ops on detecting config problems with apps?

**Comment by ggam** [comment]
@wmhopkins I still think we should try to verify correctness of parameters at deployment time, but I don't think there's enough time to come at a good solution before the spec goes final. Since the RI can do new releases as needed, probably this could be postponed to a Soteria 1.1 version. 

Btw, the spec says nothing about this behavior, so I don't think it should affect the TCK

**Comment by wmhopkins** [comment]
Closing this as **will not fix** -- using default values when a user-specified value is invalid simply masks configuration problems. It's also potentially insecure, as the resulting configuration could be less secure than the one the user was expecting based on the intended configuration.

EL validation issues are covered by other issues: #123, #104.
