### ISSUE TITLE
NPE during TCK test run

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-soteria#178]
I found another NPE exception in log, maybe because lack of permission too, but anyway,  I think should not meet NPE.

[2017-08-18T03:16:46.201-0700] [glassfish 5.0] [SEVERE] [AS-WEB-CORE-00037] [javax.enterprise.web.core] [tid: _ThreadID=30 _ThreadName=http-listener-1(5)] [timeMillis: 1503051406201] [levelValue: 1000] [[
An exception or error occurred in the container during the request processing
java.lang.NullPointerException
at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler$2.run(BaseContainerCallbackHandler.java:440)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.enterprise.security.common.AppservAccessController.doPrivileged(AppservAccessController.java:63)
at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallerPrincipal(BaseContainerCallbackHandler.java:438)
at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.processCallback(BaseContainerCallbackHandler.java:198)
at com.sun.enterprise.security.jmac.callback.ServerContainerCallbackHandler.handleSupportedCallbacks(ServerContainerCallbackHandler.java:76)
at com.sun.enterprise.security.jmac.callback.BaseContainerCallbackHandler.handle(BaseContainerCallbackHandler.java:188)
at com.sun.enterprise.security.jmac.callback.ContainerCallbackHandler.handle(ContainerCallbackHandler.java:83)
at org.glassfish.soteria.mechanisms.jaspic.Jaspic.handleCallbacks(Jaspic.java:184)
at org.glassfish.soteria.mechanisms.jaspic.Jaspic.notifyContainerAboutLogin(Jaspic.java:176)
at org.glassfish.soteria.mechanisms.HttpMessageContextImpl.doNothing(HttpMessageContextImpl.java:302)
at com.sun.ts.tests.securityapi.ham.workflow.secureresponse.TestAuthenticationMechanism.secureResponse(TestAuthenticationMechanism.java:65)
at com.sun.ts.tests.securityapi.ham.workflow.secureresponse.TestAuthenticationMechanism$Proxy$_$$_WeldClientProxy.secureResponse(Unknown Source)
at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.secureResponse(HttpBridgeServerAuthModule.java:137)
at org.glassfish.soteria.mechanisms.jaspic.DefaultServerAuthContext.secureResponse(DefaultServerAuthContext.java:80)
at com.sun.web.security.RealmAdapter.invokePostAuthenticateDelegate(RealmAdapter.java:1567)
at org.apache.catalina.authenticator.AuthenticatorBase.postInvoke(AuthenticatorBase.java:659)
at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:667)
at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:596)
at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:463)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:168)

**Comment by arjantijms** [comment]
There's two things here it seems.

First:

`secureResponse` calls `HttpMessageContextImpl.doNothing` here:

```
org.glassfish.soteria.mechanisms.HttpMessageContextImpl.doNothing(HttpMessageContextImpl.java:302)
at com.sun.ts.tests.securityapi.ham.workflow.secureresponse.TestAuthenticationMechanism.secureResponse(TestAuthenticationMechanism.java:65)
```
This causes `AuthStatus.SUCCESS` to be returned, which according to JSR 196 1.1 3.8.3.3 is not allowed. The correct status should be `AuthStatus.SEND_SUCCESS`. This is a bug in both the spec and the implementation :( 

Secondly:

The test also contains a bug and that's that it should not call `HttpMessageContextImpl.doNothing` during the call to `secureResponse`.  This results in a call to `ContainerCallbackHandler.handle` which ultimately causes the NPE.

So to fix this, the test should just return `AuthenticationStatus.SUCCESS`. That should likely fix the failure.

Implementation wise, the RI can fix the first bug by returning `AuthStatus.SEND_SUCCESS` when the outcome in `org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.secureResponse` is `AuthenticationStatus.SUCCESS`.

Something like: 

```java
AuthStatus authStatus = fromAuthenticationStatus(status);

if (authStatus == AuthStatus.SUCCESS) {
    return AuthStatus.SEND_SUCESS;
}

return authStatus;
```

Practically this is a very minor issue, and the RI can easily do the right thing here, but the spec should have mentioned this somewhere.

**Comment by wmhopkins** [comment]
@arjantijms 

Just want to make sure I understand your comment about the spec issue in "first thing" -- I see where the RI is translating _NOT_DONE_ into _SUCCESS_, but the spec is silent on the topic except for the default implementation of `secureResponse()`. Is the default impl what you meant by a bug in the spec?

For "second thing", I agree `secureResponse()` should not call `doNothing()`, or indeed, any method related to authenticating the user, and that that is the root cause of the NPE (client Subject is null). It seems `doNothing()` needs to be better documented as to what it actually does (establish an anonymous user/null caller principal), and might have benefited from a more descriptive name, but at this point it is what it is.

I think we could fix this in the RI, by noticing that the client subject is null, and throwing a different exception that's more helpful to the developer. What do you think?

**Comment by wmhopkins** [comment]
Fixed the return value from secureResponse() and added checks in handleCallbacks() for null clientSubject and null callback handler.
