### ISSUE TITLE
AccessControlException after enable SecurityManager

### ISSUE THREAD

**Issue by zjmtlab** [javaee/security-soteria#181]
After enable SecurityManager to run TCK, meet some AccessControlExceptions. Below two exceptions maybe related to Soteria. So file this issue to tracking it.  Please help to check whether these are Soteria bugs. Thanks!

Issue1:

java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getPolicy")
[2017-08-20T19:29:40.406-0700] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=26 _ThreadName=http-listener-1(4)] [timeMillis: 1503282580406] [levelValue: 900] [[
  StandardWrapperValve[com.sun.ts.tests.securityapi.securitycontext.authenticate.Servlet]: Servlet.service() for servlet com.sun.ts.tests.securityapi.securitycontext.authenticate.Servlet threw exception
java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getPolicy")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.security.Policy.getPolicy(Policy.java:153)
        at org.glassfish.soteria.authorization.JACC.hasPermission(JACC.java:122)
        at org.glassfish.soteria.authorization.JACC.isCallerInRole(JACC.java:77)
        at org.glassfish.soteria.authorization.spi.impl.ReflectionAndJaccCallerDetailsResolver.isCallerInRole(ReflectionAndJaccCallerDetailsResolver.java:81)
        at org.glassfish.soteria.SecurityContextImpl.isCallerInRole(SecurityContextImpl.java:88)
        at com.sun.ts.tests.securityapi.securitycontext.authenticate.Servlet.doGet(Servlet.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:316)
        at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:314)
 
Issue2:

java.security.AccessControlException: access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")  [2017-08-20T20:12:15.763-0700] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=25 _ThreadName=http-listener-1(1)] [timeMillis: 1503285135763] [levelValue: 900] [[    StandardWrapperValve[com.sun.ts.tests.securityapi.ham.workflow.cleansubject.Servlet]: Servlet.service() for servlet com.sun.ts.tests.securityapi.ham.workflow.cleansubject.Servlet threw exception  java.security.AccessControlException: access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")          at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)          at java.security.AccessController.checkPermission(AccessController.java:884)          at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)          at javax.security.auth.Subject$SecureSet$1.remove(Subject.java:1084)          at javax.security.auth.Subject$SecureSet.clear(Subject.java:1300)          at java.util.Collections$SynchronizedCollection.clear(Collections.java:2054)          at org.glassfish.soteria.mechanisms.jaspic.Jaspic.cleanSubject(Jaspic.java:145)          at org.glassfish.soteria.mechanisms.HttpMessageContextImpl.cleanClientSubject(HttpMessageContextImpl.java:131)          at javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism.cleanSubject(HttpAuthenticationMechanism.java:139)          at com.sun.ts.tests.securityapi.ham.workflow.cleansubject.TestAuthenticationMechanism.cleanSubject(TestAuthenticationMechanism.java:60)          at com.sun.ts.tests.securityapi.ham.workflow.cleansubject.TestAuthenticationMechanism$Proxy$_$$_WeldClientProxy.cleanSubject(Unknown Source)          at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.cleanSubject(HttpBridgeServerAuthModule.java:162)          at org.glassfish.soteria.mechanisms.jaspic.DefaultServerAuthContext.cleanSubject(DefaultServerAuthContext.java:85)          at com.sun.web.security.RealmAdapter.logout(RealmAdapter.java:478)          at org.apache.catalina.connector.Request.logout(Request.java:2122)          at org.apache.catalina.connector.RequestFacade.logout(RequestFacade.java:1154)          at com.sun.ts.tests.securityapi.ham.workflow.cleansubject.Servlet.doGet(Servlet.java:46)          at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)          at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)          at java.lang.reflect.Method.invoke(Method.java:498)          at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:316)          at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:314)          at java.security.AccessController.doPrivileged(Native Method)          at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)          at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:349)          at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:207)

**Comment by wmhopkins** [comment]
Added `PrivilegedAction` blocks to address both access control problems (and some others that were lurking in JACC.java).
