### ISSUE TITLE
NameNotFoundException if invalid groupBaseDn  property in LdapIdentityStore

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#85]
Similar exception appears as Issue2 in #79 
when invalid groupBaseDn specified
Since bug#79 is fixed, I opened this bug to track this issue

@ldapidentitystoredefinition(
url = "ldap://localhost:11389/",
callerBaseDn = "ou=caller,dc=securityapi,dc=net",
groupBaseDn = "ou=invalid,dc=securityapi,dc=net"
)
[2017-06-19T21:26:49.183-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=26 _ThreadName=Thread-9] [timeMillis: 1497932809183] [levelValue: 1000] [[
java.lang.IllegalStateException: javax.naming.NameNotFoundException: [LDAP: error code 32 - The search base entry 'ou=invalid,dc=securityapi,dc=net' does not exist]; remaining name 'ou=invalid,dc=securityapi,dc=net'
at org.glassfish.soteria.identitystores.LdapIdentityStore.search(LdapIdentityStore.java:276)
at org.glassfish.soteria.identitystores.LdapIdentityStore.retrieveGroupInformation(LdapIdentityStore.java:218)
at org.glassfish.soteria.identitystores.LdapIdentityStore.checkDirectBinding(LdapIdentityStore.java:196)
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:96)
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:87)

**Comment by wxwesther** [comment]
groupBaseDn is changed to groupSearchBase .
And similar exception returns when use invalid groupSearchBase  .

@LdapIdentityStoreDefinition(
		url = "ldap://localhost:11389/",
	    callerBaseDn = "ou=caller,dc=securityapi,dc=net",
	    groupSearchBase  = "ou=invalid,dc=securityapi,dc=net"
)

**Comment by wmhopkins** [comment]
This issue is indeed similar to #79 , but I believe the resolution of #79 is incorrect. `IdentityStores` should throw exceptions to indicate configuration or runtime processing errors like network errors.

**Comment by wmhopkins** [comment]
Updated `LdapIdentityStore` to ensure consistent exception handling. Where possible to detect, `IdentityStoreConfigurationExceptions` are thrown; if not, and if an error results, an `IdentityStoreRuntimeException` is thrown
